### ISSUE TITLE
Crashed on  version 1.20.1

### ISSUE THREAD

**Issue by oof100200** [Leclowndu93150/Pretty-Rain#1]
https://pastebin.com/fDdncC3N

**Comment by Leclowndu93150** [comment]
hm okay

**Comment by Leclowndu93150** [comment]
does it happen just once or always ?

**Comment by oof100200** [comment]
> does it happen just once or always ?

When it rains.

**Comment by oof100200** [comment]
> does it happen just once or always ?

Still crashed on version 1.0.3, log: https://pastebin.com/RM9eRCLp

**Comment by Leclowndu93150** [comment]
Im looking at it

**Comment by oof100200** [comment]
> Im looking at it

thanks

**Comment by Leclowndu93150** [comment]
try this http://temp.sh/FQWKn/particlerain-1.0.4.jar

**Comment by oof100200** [comment]
> try this http://temp.sh/FQWKn/particlerain-1.0.4.jar

still crahsed: https://pastebin.com/hRGNuBiz

**Comment by Leclowndu93150** [comment]
can you send me your modpack ?

**Comment by oof100200** [comment]
> can you send me your modpack ?

sure, i will contact ur discord.

**Comment by Leclowndu93150** [comment]
now fixed in 1.0.4
