### ISSUE TITLE
[1.20.1] No weather when looking through stained glass

### ISSUE THREAD

**Issue by xhatz** [Leclowndu93150/Pretty-Rain#10]
Latest version 1.20.1 for Forge! When looking through any teinted glass (vanilla stained glass, hearth and home stained), the weather particles completely disappear :o

Clear glass like vanilla or Create's glass works.

Edit: nevermind I think it's an Embeddium bug, setting graphics to Fabulous fixed it (did this with other weather mods too).

**Comment by Leclowndu93150** [comment]
completed ?
