### ISSUE TITLE
Flickering Sand + other particles 

### ISSUE THREAD

**Issue by Lacie-Veil** [Leclowndu93150/Pretty-Rain#2]
Here's the video!

https://www.youtube.com/watch?v=30XwQaeEXsk

**Comment by Leclowndu93150** [comment]
thank you !, so the desert particles aren't really flickering it's mean to be like that, but the campire is def a bug

**Comment by Leclowndu93150** [comment]
actually now that im looking at it, you're not wrong im idiot

**Comment by Leclowndu93150** [comment]
I've contacted the Forge developers as it's a bug on their side
