### ISSUE TITLE
Splashes have no texture

### ISSUE THREAD

**Issue by mxnmnm** [Leclowndu93150/Pretty-Rain#3]
![2024-12-23_16 44 16](https://github.com/user-attachments/assets/02393ac1-c934-4af2-9551-a7337dce06f4)

**Comment by mxnmnm** [comment]
this is on 1.20.1 btw

**Comment by Leclowndu93150** [comment]
works just fine for me, with a new instance and the mod. do you have any other additional mods installed ?

**Comment by mxnmnm** [comment]
yea a lot of them hmmm guess i'll have to figure out which one is causing the issue. I will update when i find the culprit (binary search ftw)

**Comment by Leclowndu93150** [comment]
binary search ftw !

**Comment by Leclowndu93150** [comment]
actually i reported 1.20.1 again 
http://temp.sh/YlWcz/particlerain-1.0.4.jar
can you try with this one ?

**Comment by mxnmnm** [comment]
Well that just saved me a lot of time :D

**Comment by Leclowndu93150** [comment]
great
